"""Add message replies

Revision ID: 7a8ca3c02b74
Revises: d54721907172
Create Date: 2026-10-08 02:25:56.865226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8ca3c02b74'
down_revision = 'd54721907172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_message_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_reply_to_message_id'), ['reply_to_message_id'], unique=False)
        batch_op.create_foreign_key('fk_messages_reply_to_message_id', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_reply_to_message_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_reply_to_message_id'))
        batch_op.drop_column('reply_to_message_id')

    # ### end Alembic commands ###
