"""Add voice message fields

Revision ID: 7fdfc96c1cc9
Revises: 9701027102ce
Create Date: 2026-10-09 21:01:24.005562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdfc96c1cc9'
down_revision = '9701027102ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audio_original_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audio_duration_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('audio_duration_ms')
        batch_op.drop_column('audio_original_name')
        batch_op.drop_column('audio_filename')

    # ### end Alembic commands ###
