"""Add message deletion fields

Revision ID: 94e7dc552f50
Revises: d41acaa3a35c
Create Date: 2026-10-08 00:28:33.980791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e7dc552f50'
down_revision = 'd41acaa3a35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_for_sender_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_for_receiver_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_for_everyone_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('deleted_for_everyone_at')
        batch_op.drop_column('deleted_for_receiver_at')
        batch_op.drop_column('deleted_for_sender_at')

    # ### end Alembic commands ###
