"""Add image message fields

Revision ID: 9701027102ce
Revises: e6796fcf78bc
Create Date: 2026-10-09 01:22:02.858732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9701027102ce'
down_revision = 'e6796fcf78bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), server_default='text', nullable=False))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_original_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('image_original_name')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
