"""Add video message fields

Revision ID: d8a04421f33d
Revises: 7fdfc96c1cc9
Create Date: 2026-10-10 04:02:24.412842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a04421f33d'
down_revision = '7fdfc96c1cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_original_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('video_original_name')
        batch_op.drop_column('video_filename')

    # ### end Alembic commands ###
